import 'package:get/get.dart';

class AppTranslations extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en': {
      //login
      'login':'Login',
      'password': 'Password',
      'login_subtitle':'Please login to give your presence.',
      'login_title':'Welcome to Family Planning Smart Monitoring System!',
      'attendance': 'Attendance',
      'home':'Home',
      'settings': 'Settings',
      'change_language': 'Change Language',
      'personal_info': 'Personal Information',
      'attendance_history': 'Attendance History',
      "id_number":"Id Number",
      //profile
      'profile':"Profile",
     'leave_application': 'Leave Application',
     'change_password': 'Change Password',
      'logout': 'Log Out',
      'employee_name': 'Employee Name',
      'mobile_number': 'Mobile Number',
      'nid_number': 'National ID Number',
      'previous_applications': 'Previous Applications',
      'add_new_application': 'Add New Application',
      'submit_leave_application': 'Submit Leave Application',
      'name':"Name",
      'age':'Age',
      'address':'Address',
      'privacy_policy':'Privacy Policy',

      'conditions':"Conditions",
      "guidelines":"Guidelines",

      'date': 'Date',
      'time':"Time",
      'leave_type': 'Leave Type',
      'leave_reason': 'Leave Reason',
      'current_password': 'Current Password',
      'new_password': 'New Password',
      'confirm_new_password': 'Confirm New Password',
      'family_planning': 'Family Planning Smart Monitoring',

      //attedance verify
      'work_type': 'Work Type',
      'couple_num': 'Couple Number',
      'couple_name': 'Couple Name',
      'husband_name': 'Husband Name',
      'children_count': 'Number of Children',
      'short_address': 'Short Address',
      'map_address': 'Address on Map',
      'description': 'Description',
      'method_name': 'Method Name',
      'picture': 'Picture',
     'summary':"Summary",
      "attendance_list":"Attendance List",
     'service_type': "Service Type",
     'method_recipients':'Number Of Method Recipients',
      'teenager':'Teenager',
      'child':'Child',
      'pregnant_mother':'Pregnant Mother',
      'couple':'Couple',
      'other':'Other',
      'camp_attend':'Camp Attendance',
      'client_name':'Client Name',
      'principal_name':'Principal Name',
      'school_name':'School Name',
      'place':'Place',
      'service_name':'Service Name',
      "attendance_type":"Attendance Type",
      "select_date":"Select The Date",
      'view_attendance_history':'View_Attendance_History',

      //homeview
      'latest_attendance': 'Latest Attendance',
      'attendance_given_today': 'Attendance Given Today',
      'submit_new_attendance': 'Submit New Attendance',
      'submit_attendance': 'Submit Attendance',
      'timely_attendance': 'Timely Attendance',
      'view_activities_history': 'View Activities History',
      'late_attendance': 'Late Attendance',
      'validate_fwa': 'Validate FWA',
      'total_fwa_attendance': 'Total FWA Attendance',
      'apply_leave': 'Leave Application',
      'submit_leave':"Submit Leave Application Form",
      'welcome': 'Welcome',
      "leave_cz": "Reason for the holiday",
      'leave_type': 'Leave Type',
      "notice":"Notice",
      "fwa_validation":"FWA Validation",
      "regarding_attendance":"Regarding Attendance",

      'application_date':'Application Date',
      "application_picture":" Application Picture",
      'help_report':'Help & Report',
      'give_feedback':'Give Feedback',
      'submit':'Submit',
      'subject':'Subject',
      'student_num':'Student Number',
      'prottayon_pic':"Verification Picture",
      'activities':'Activities',
      'total_activities':'Total Activities',

      ///month
  'month_01': 'January',
  'month_02': 'February',
  'month_03': 'March',
  'month_04': 'April',
  'month_05': 'May',
  'month_06': 'June',
  'month_07': 'July',
  'month_08': 'August',
  'month_09': 'September',
  'month_10': 'October',
  'month_11': 'November',
  'month_12': 'December',

    },
    'bn': {

      //login
      'login_subtitle':'আপনার উপস্থিতি দিতে লগইন করুন',
      'login_title':'পরিবার পরিকল্পনা স্মার্ট মনিটরিং সিস্টেমে আপনাকে স্বাগতম!',
      "attendance":"উপস্থিতি",
      'settings': 'সেটিংস',
        "home":"হোম",
      'change_language': 'ভাষা পরিবর্তন',
      'personal_info': 'ব্যাক্তিগত তথ্য',
      'attendance_history' : 'উপস্থিতি হিস্টোরি',
      'leave_application': 'ছুটির আবেদন',
      'change_password': 'পাসওয়ার্ড পরিবর্তন',
       'profile':'প্রোফাইল',
      "id_number":"আইডি নম্বর",
      'logout':'লগ আউট',
      'login':'লগইন করুন',
      'employee_name': 'কর্মীর নাম',
      'mobile_number': 'মোবাইল নাম্বার',
      'nid_number': 'জাতীয় পরিচয়পত্র নাম্বার',
      'previous_applications': 'পূর্বের আবেদন',
      'add_new_application': 'নতুন আবেদন যোগ করুন',
      'submit_leave_application': 'ছুটির আবেদন জমা দিন',
      'date': 'তারিখ',
      'leave_type': 'ছুটির ধরন',
      'leave_reason': 'ছুটির কারণ',
      'current_password': 'বর্তমান পাসওয়ার্ড',
      'password_change': 'পাসওয়ার্ড',
      'new_password': 'নতুন পাসওয়ার্ড',
      'password': 'পাসওয়ার্ড',
      'confirm_new_password': 'নতুন পাসওয়ার্ড কনফার্ম',
      'family_planning': 'পরিবার পরিকল্পনা স্মার্ট মনিটরিং ',

      //attendance
      'place':'স্থান',
      'time':"সময়",
      "submit_attendance":"উপস্থিতি জমা দিন",
      'work_type': 'কাজের ধরণ',
      'couple_num': 'দম্পতি নাম্বার',
      'couple_name': 'দম্পতির নাম',
      'husband_name': 'স্বামীর নাম',
      'children_count': 'ছেলে-মেয়ের সংখ্যা',
      'short_address': 'সংক্ষিপ্ত ঠিকানা',
      'map_address': 'মানচিত্রে ঠিকানা',
      'description': 'বিবরণ',
      'method_name': 'পদ্ধতির নাম',
      'picture': 'ছবি',
      "summary":"সারমর্ম",
      "attendance_list":"উপস্থিতির তালিকা",
      'service_type':'সেবার ধরন',
      'method_recipients':'পদ্ধতি গ্রহীতার সংখ্যা',
      'teenager':'কিশোর কিশোরী',
      'child':'শিশু',
      'pregnant_mother':'গর্ভবতী মা',
      'couple':'দম্পতি',
      'other':'অন্যান্য',
      'client_name':'ক্লায়েন্টের নাম',
      'principal_name':'প্রধান শিক্ষকের নাম',
      'school_name':'স্কুলের নাম',
      'service_name':"সেবার নাম",
      "attendance_type":'উপস্থিতির ধরণ',
      "select_date":"তারিখ নির্বাচন করুন",

      //homeview
      'latest_attendance': 'সর্বশেষ উপস্থিতি',
      'attendance_given_today': 'আজ উপস্থিতি দিয়েছেন',
      'submit_new_attendance': 'নতুন উপস্থিতি জমা দিন',
      'timely_attendance': 'সময়মত উপস্থিতি',
      'view_activities_history': 'কার্যক্রমসমূহের হিস্টোরি দেখুন',
      "view_attendance_history":"উপস্থিতির হিস্টোরি দেখুন",
      'late_attendance': 'দেরীতে উপস্থিতি',
      'validate_fwa': 'এফডব্লিউএ ভ্যালিডেট করুন',
      'total_fwa_attendance': 'আজকে মোট এফডব্লিউএ উপস্থিতি',
      'apply_leave': 'ছুটির আবেদন',
      "submit_leave":"ছুটির আবেদনপত্র জমা দিন",
      'welcome':'স্বাগতম',
      'activities':'কার্যক্রমসমূহ',
      'total_activities':"আজকের দিনের মোট কার্যক্রম",
      "fwa_validation":"এফডব্লিউএ ভ্যালিডেট",
      "regarding_attendance":"উপস্থিতি সংক্রান্ত",

      //profile
      'name':"নাম",
      'age':'বয়স',
      'address':'ঠিকানা',
      'camp_attend':"কেন্দ্র উপস্থিতি",
      'leave_cz': 'ছুটির কারন',
      'leave_type': 'ছুটির ধরন',
      'notice':'নোটিশ',
      'application_date':'আবেদনের তারিখ',
      'application_picture':'আবেদনের ছবি',
      'help_report': 'হেল্প এবং রিপোর্ট',
      "give_feedback" : "মতামত দিন",
      'submit':'জমা দিন',
      'subject':"বিষয়",
      'student_num':"ছাত্রছাত্রীর সংখ্যা",
      'prottayon_pic':'প্রত্যায়নের ছবি',
      'privacy_policy':"প্রাইভেসি পলিসি",
      'conditions': "শর্তাবলী",
       "guidelines":"নির্দেশিকা",

      ///month
      'month_01': 'জানুয়ারি',
      'month_02': 'ফেব্রুয়ারি',
      'month_03': 'মার্চ',
      'month_04': 'এপ্রিল',
      'month_05': 'মে',
      'month_06': 'জুন',
      'month_07': 'জুলাই',
      'month_08': 'আগস্ট',
      'month_09': 'সেপ্টেম্বর',
      'month_10': 'অক্টোবর',
      'month_11': 'নভেম্বর',
      'month_12': 'ডিসেম্বর',
    },
  };


}

